version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    labels:
      - 'dependencies'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '02:34'
    groups:
      production:
        dependency-type: 'production'
        patterns:
          - '*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
      development:
        dependency-type: 'development'
        patterns:
          - '*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
    commit-message:
      include: 'scope'
      prefix: 'chore(deps): '
    allow:
      - dependency-type: 'all'
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
